### ISSUE TITLE
Set executor priorities

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#10]
**Is your feature request related to a problem? Please describe.**
If you have multiple exectutors and you want to primarily use one and have the second one for specific extreme situations then you can not do that. At the moment a worker/executor is choosen randomly.

**Describe the solution you'd like**
Set prioties as in a ranking.

**Comment by code-for-fish** [comment]
Dear @Aequalitas, 
thank you for your support :-) In Release 0.0.0 we will have a new "Executor Model". Executors are now Workers and a Worker will execute a Script in a specific ENV. There is also a priority based scheduling right now. Please see https://lost.readthedocs.io/en/latest/all_about_scripts.html#script-envs for more information.
