### ISSUE TITLE
Docker compose | manifest unknown

### ISSUE THREAD

**Issue by pepijnob** [l3p-cv/lost#104]
Hi I'm following the quicksetup and run into this issue when running 'docker-compose up' on windows: 

ERROR: manifest for l3pcv/lost-cv:latest not found: manifest unknown: manifest unknown

I tried to change latest to 1.1 or 1.2, but that doesn't help, I also couldn't find a fix on google. Is there some issue with the manifest itself or is there some work around?

**Comment by jaeger-j** [comment]
Hi @pepijnob,
you can use tag **1.2.0** for example. See https://github.com/l3p-cv/lost/releases for all possible releases.
Best,
Jonas
