### ISSUE TITLE
Documentation for local build

### ISSUE THREAD

**Issue by sokolegg** [l3p-cv/lost#105]
Hi, I want to understand how to build your project locally without Dockerhub. In my case I want to modify some backend code (roles logic) and rebuild project to test it.

Is it possible to share some information here or in the documentation?

**Comment by jaeger-j** [comment]
Hi @sokolegg,
we created a documentation for local docker builds. Please checkout https://lost.readthedocs.io/en/1.3/contribution_guide.html
Best,
Jonas

**Comment by sokolegg** [comment]
@jaeger-j  Thanks!
