### ISSUE TITLE
Fix blocking of annotations

### ISSUE THREAD

**Issue by sokolegg** [l3p-cv/lost#107]
I have a problem that no one can label blocked annotation images.  The annotator who got these images in annotation not in the team now. We have this problem due to this code in logic/mia:

```python
def __get_next_image_anno(db_man, user_id, at, max_amount):
    """...."""
    ################## get new (unlocked)############################
    # first get random sim class
    sim_class = db_man.get_random_sim_class_img_anno(at.idx)
    if sim_class:
        sim_class = sim_class.sim_class
    else:
        images = dict()
        images['images'] = list()
        return images
    """...."""
```
I saw that you have auto-release of blocked tasks, but it doesn't work (we have waited for three days) 
It probably due to this configuration in celeryconfig.py

```
    ...
    'release_annos': {
        'task': 'lost.logic.tasks.release_annos',
        'schedule': int(LOST_CONFIG.session_timeout)*60
    }
```

**Comment by jaeger-j** [comment]
Hi @sokolegg,
thank you for your contribution. Could you please provide your lost **version** and the `lost/data/logs/lost-0.log` log file

**Comment by gereonreus** [comment]
Fixed in 2.x.
