### ISSUE TITLE
deleting pipeline does not work everytime

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#11]
**Describe the bug**
When i click on the delete pipeline button then i will be redirected to the pipelines overview and often the pipeline still exists. Deleting works like only every fourth time i pressed the delete button. 

**Expected behavior**
Only redirect when the deletion is confirmed. Display a loading symbol/message

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by gereonreus** [comment]
Solved. Will be part of Release 0.0.0
