### ISSUE TITLE
SIA: Mounting of image directory after hosting lost is treated as empty directory

### ISSUE THREAD

**Issue by Avni-Hirpara** [l3p-cv/lost#110]
**Description of the bug**
Ideally when we put image directory inside 'data/media', application is able to recognise directory and images during pipeline creation and pipeline execution. If image directory inside 'data/media' is mounted, lost application is able to recognise directory name while creating pipeline however it is not able to recognise image inside that directory while pipeline execution(during annotation it fails with 0 images) even if necessary permission is given to that directory.

**To Reproduce**
Steps to reproduce the behaviour:
1. host lost with 'no_ai' set up in some VM.
2. Create another directory inside 'data/media' and mount that with some different directory with images.
3. Check for shared images inside 'data/media/img-dir' and permissions.
4. Create new pipeline with 'img-dir' mounted image directory.
5. During the annotation task, Application is showing 0/0 result.

**Expected behavior**
It should recognise images inside mounted directory.

**Screenshots**
Please find attachment for the same.
![BrokenPipeline](https://user-images.githubusercontent.com/61819887/98185339-719ef200-1f32-11eb-998b-ffef7116369d.png)
![Show0Image](https://user-images.githubusercontent.com/61819887/98185341-74014c00-1f32-11eb-9153-70a3b207988e.png)

**Desktop (please complete the following information):**
 - Application is hosted on ubuntu 16.04
 - Browser: Running it on windows chrome browser 

**Additional comments**
 - It fails the pipeline at script node due to blank dataframe (no annotation details). And data Export goes for pending state for long

**Comment by gereonreus** [comment]
Hello Avni-Hirpara,

can you please tell me how exactly the folder was mounted in **data/media** ?

The whole **data** folder should already be mounted to the host system using the docker. 

Have you mounted a network share in the host system into this folder ?
If so, what kind of share is it (NFS / SMB) ?

Best regards,
Gereon

**Comment by Avni-Hirpara** [comment]
I know we have to mount data folder with host and it is already being done through docker-compose.yml.

In addition to that I have to mount image folder from third party s3fs bucket to do annotation. when I am mounting any bucket with a folder in media directory prior to hosting LOST application it is working fine and I am able to access images inside that bucket through LOST at annotation task. however If I mount new folder inside media during application is running. Changes are not reflected. I mean, I can see newly mounted folder in pipeline creation dropdown. But at the annotation task, It appears as blank folder. I am not able to access bucket images.

**Comment by Avni-Hirpara** [comment]
Any update on this?

**Comment by gereonreus** [comment]
Hello Avni-Hirpara,

sorry for the late reply.
Unfortunately, due to the lack of experience with s3fs, I can not explain whats the reason for your error.

Maybe the new filesystem abstraction feature in LOST will help you in the future:
By using the fsspec library it should be possible to use the following filesystems in the future:
[Supported FS by fsspec](https://filesystem-spec.readthedocs.io/en/latest/_modules/fsspec/registry.html#register_implementation
)

Users should then be able to add any number of data sources (also from independent/different filesystems).
 
Kind regards,
Gereon

**Comment by gereonreus** [comment]
Already implemented on branch 2.x
