### ISSUE TITLE
SIA: deleting anno by close-X deletes it also from history

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#12]
**Describe the bug**
When deleting an annotation by clicking to the close cross in the right top corner it can not be received back via CTRL+Z keyboard combination

**Expected behavior**
When deleting the annotation by pressing the DEL key it is saved in the history and can be received back with CTRL+Z

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrom

**Comment by gereonreus** [comment]
Fixed in 0.0.0
