### ISSUE TITLE
Database Interface as additional data source

### ISSUE THREAD

**Issue by devthrough** [l3p-cv/lost#121]
**Is your feature request related to a problem? Please describe.**
To get rid out of copying folders and add data in a continuous manner .
**Describe the solution you'd like**
Adding a database interface as data source to get continuous data without user interaction. 

**Describe alternatives you've considered**
Cloud storages (e.g. Google Drive, Dropbox, ...).

**Additional context**
-

**Comment by gereonreus** [comment]
Implemented in 2.x using fsspec module.
External filesystems tested so far: S3 Bucket, Azure Blobstorage, FTP / SHH
