### ISSUE TITLE
MIA: showProposedLabel doesn't work

### ISSUE THREAD

**Issue by m-hamstra** [l3p-cv/lost#128]
**Describe the bug**
When the "**showProposedLabel**" option in an MIA type AnnoTask is set to **true**, the proposed label isn't shown in the MIA annotator view.

**Expected behavior**
When **showProposedLabel** is enabled and the sim_class is provided in the script before the annotation task, we expect that class to be pre-selected in the label dropdown list or at least be visible somewhere in the MIA view.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox

**Additional context**
The get_proposed_label method in the back-end module logic.mia doesn't process the output from get_label_trees() correctly and suppresses the exception that occurs.
The front-end appears to not process the **proposedLabel** from the getMiaAnnos response at all.

**Comment by gereonreus** [comment]
Duplicate with #44
