### ISSUE TITLE
SIA: Deleting an annoation with the the top-right corner X not possible when...

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#13]
**Describe the bug**
...it was deleting before with the DEL key and was received back from the history with CTRL+Z

**To Reproduce**
1. Delete an annotation with the DEL key
2. Receive it back with the keyboard combination CTRL+Z
3. Now try to delete the annotation with the close-X in the right top corner of the annotation
4. Does not work

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by gereonreus** [comment]
Fixed.
