### ISSUE TITLE
Change port on docker?

### ISSUE THREAD

**Issue by kevkid** [l3p-cv/lost#137]
Not really a bug.

How do I change the port of the docker image. I have stuff running on port 80 and 8080. I would like to run it on port 8081. In the quick_setup.py I changed this line to reflect this:
`['LOST_FRONTEND_PORT', 8081],`
and changed the docker-compose.yml to have 
```
      ports:
        - "${LOST_FRONTEND_PORT}:8081"
```

This didnt work. How can I do this?

**Comment by JonasGoebel** [comment]
You'll have to change the Port inside your .env file.
1. Go to your installation directory
2. cd docker
3. editor .env
4. There you can change the LOST_FRONTEND_PORT to 8081
5. exit the editor and run `docker-compose up`
LOST should now be running on port 8081

**Comment by kevkid** [comment]
> You'll have to change the Port inside your .env file.
> 
> 1. Go to your installation directory
> 2. cd docker
> 3. editor .env
> 4. There you can change the LOST_FRONTEND_PORT to 8081
> 5. exit the editor and run `docker-compose up`
>    LOST should now be running on port 8081

Thank you this worked!
