### ISSUE TITLE
Polygon point is offset after switching to new image

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#14]
**Describe the bug**
Sometimes when i switch to a new image to annotate and i want to start with the annotation the point for the polygon is randomly offset to the mouse pointer. It does happen randomly about every ten images. Can not reproduce the bug.
 Can be probaply fixed when the position of the mouse pointer is reset for every image.

**Expected behavior**
The point is set where the mouse pointer is.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

Thanks for the work guys!

**Comment by code-for-fish** [comment]
Should be fixed in release 0.0.0
