### ISSUE TITLE
ModuleNotFoundError: No module named 'lost'

### ISSUE THREAD

**Issue by chaoji90** [l3p-cv/lost#158]
**Describe the bug**
I get started exactly follow the orders
git clone https://github.com/l3p-cv/lost.git   
cd lost/docker/quick_setup/  
python3 quick_setup.py ~/lost -noai  
docker-compose up  

Then I got the following error message
db-lost    | 2021-10-30 13:25:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
db-lost    | 2021-10-30 13:25:42+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-lost    | 2021-10-30 13:25:42+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
db-lost    | 2021-10-30T13:25:43.027696Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db-lost    | 2021-10-30T13:25:43.029698Z 0 [Note] mysqld (mysqld 5.7.36) starting as process 1 ...
db-lost    | 2021-10-30T13:25:43.032604Z 0 [Note] InnoDB: PUNCH HOLE support available
db-lost    | 2021-10-30T13:25:43.032618Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db-lost    | 2021-10-30T13:25:43.032622Z 0 [Note] InnoDB: Uses event mutexes
db-lost    | 2021-10-30T13:25:43.032625Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db-lost    | 2021-10-30T13:25:43.032628Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db-lost    | 2021-10-30T13:25:43.032632Z 0 [Note] InnoDB: Using Linux native AIO
db-lost    | 2021-10-30T13:25:43.032880Z 0 [Note] InnoDB: Number of pools: 1
db-lost    | 2021-10-30T13:25:43.032991Z 0 [Note] InnoDB: Using CPU crc32 instructions
db-lost    | 2021-10-30T13:25:43.034789Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db-lost    | 2021-10-30T13:25:43.042847Z 0 [Note] InnoDB: Completed initialization of buffer pool
db-lost    | 2021-10-30T13:25:43.045266Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db-lost    | 2021-10-30T13:25:43.057099Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db-lost    | 2021-10-30T13:25:43.058431Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12661000
db-lost    | 2021-10-30T13:25:43.058440Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12661009
db-lost    | 2021-10-30T13:25:43.058444Z 0 [Note] InnoDB: Database was not shutdown normally!
db-lost    | 2021-10-30T13:25:43.058447Z 0 [Note] InnoDB: Starting crash recovery.
db-lost    | 2021-10-30T13:25:43.208219Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db-lost    | 2021-10-30T13:25:43.208250Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db-lost    | 2021-10-30T13:25:43.208407Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db-lost    | 2021-10-30T13:25:43.345036Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db-lost    | 2021-10-30T13:25:43.346355Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db-lost    | 2021-10-30T13:25:43.346371Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db-lost    | 2021-10-30T13:25:43.346895Z 0 [Note] InnoDB: Waiting for purge to start
db-lost    | 2021-10-30T13:25:43.397101Z 0 [Note] InnoDB: 5.7.36 started; log sequence number 12661009
db-lost    | 2021-10-30T13:25:43.397375Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db-lost    | 2021-10-30T13:25:43.397703Z 0 [Note] Plugin 'FEDERATED' is disabled.
db-lost    | 2021-10-30T13:25:43.402766Z 0 [Note] InnoDB: Buffer pool(s) load completed at 211030 13:25:43
db-lost    | 2021-10-30T13:25:43.411239Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db-lost    | 2021-10-30T13:25:43.411270Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db-lost    | 2021-10-30T13:25:43.411278Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
db-lost    | 2021-10-30T13:25:43.411287Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
db-lost    | 2021-10-30T13:25:43.412810Z 0 [Warning] CA certificate ca.pem is self signed.
db-lost    | 2021-10-30T13:25:43.412885Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db-lost    | 2021-10-30T13:25:43.414296Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db-lost    | 2021-10-30T13:25:43.415271Z 0 [Note] IPv6 is available.
db-lost    | 2021-10-30T13:25:43.415296Z 0 [Note]   - '::' resolves to '::';
db-lost    | 2021-10-30T13:25:43.415340Z 0 [Note] Server socket created on IP: '::'.
db-lost    | 2021-10-30T13:25:43.417127Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db-lost    | 2021-10-30T13:25:43.433654Z 0 [Note] Event Scheduler: Loaded 0 events
db-lost    | 2021-10-30T13:25:43.433949Z 0 [Note] mysqld: ready for connections.
db-lost    | Version: '5.7.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db-lost    | 2021-10-30T13:25:43.854414Z 2 [Note] Got an error reading communication packets
lost       | Traceback (most recent call last):
lost       |   File "/code/backend/lost/logic/init/initlost.py", line 4, in <module>
lost       |     from lost.db import access
lost       | ModuleNotFoundError: No module named 'lost'
lost       | import_examples.sh: line 1: [: =: unary operator expected
lost       | /code/backend/lost/cli
lost       | Running Sphinx v3.2.1
lost       | making output directory... done
lost       | WARNING: html_static_path entry '_static' does not exist
lost       | building [mo]: targets for 0 po files that are out of date
lost       | building [html]: targets for 15 source files that are out of date
lost       | updating environment: [new config] 15 added, 0 changed, 0 removed
lost       | reading sources... [  6%] advanced_setup
lost       | reading sources... [ 13%] all_about_pipelines
lost       | reading sources... [ 20%] all_about_scripts
lost       | reading sources... [ 26%] annotation_review
lost       | reading sources... [ 33%] annotators
lost       | reading sources... [ 40%] contribution_guide
lost       | reading sources... [ 46%] conventions
lost       | reading sources... [ 53%] designers
lost       | reading sources... [ 60%] getting_started
lost       | reading sources... [ 66%] index
lost       | reading sources... [ 73%] lost_cli
lost       | reading sources... [ 80%] lost_ecosystem
lost       | reading sources... [ 86%] pyapi
lost       | reading sources... [ 93%] quick_setup
lost       | reading sources... [100%] users_groups
lost       |
lost       | looking for now-outdated files... none found
lost       | pickling environment... done
lost       | checking consistency... done
lost       | preparing documents... done
lost       | writing output... [  6%] advanced_setup
lost       | writing output... [ 13%] all_about_pipelines
lost       | writing output... [ 20%] all_about_scripts
lost       | writing output... [ 26%] annotation_review
lost       | writing output... [ 33%] annotators
lost       | writing output... [ 40%] contribution_guide
lost       | writing output... [ 46%] conventions
lost       | writing output... [ 53%] designers
lost       | writing output... [ 60%] getting_started
lost       | writing output... [ 66%] index
lost       | writing output... [ 73%] lost_cli
lost       | writing output... [ 80%] lost_ecosystem
lost       | writing output... [ 86%] pyapi
lost       | writing output... [ 93%] quick_setup
lost       | writing output... [100%] users_groups
lost       |
lost       | generating indices...  genindex py-modindexdone
lost       | highlighting module code... [  9%] lost.db.dtype
lost       | highlighting module code... [ 18%] lost.db.model
lost       | highlighting module code... [ 27%] lost.logic.label
lost       | highlighting module code... [ 36%] lost.pyapi.inout
lost       | highlighting module code... [ 45%] lost.pyapi.pipe_elements
lost       | highlighting module code... [ 54%] lost.pyapi.pipeline
lost       | highlighting module code... [ 63%] lost.pyapi.script
lost       | highlighting module code... [ 72%] lost.pyapi.utils.anno_helper
lost       | highlighting module code... [ 81%] lost.pyapi.utils.blacklist
lost       | highlighting module code... [ 90%] lost.pyapi.utils.vis
lost       | highlighting module code... [100%] sqlalchemy.orm.attributes
lost       |
lost       | writing additional pages...  searchdone
lost       | copying images... [  5%] images/lost-review-btn.png
lost       | copying images... [ 11%] images/lost-review-sia.png
lost       | copying images... [ 17%] images/lost-review-filter.png
lost       | copying images... [ 23%] images/annotator-dashboard.png
lost       | copying images... [ 29%] images/sia-example.png
lost       | copying images... [ 35%] images/sia-canvas.png
lost       | copying images... [ 41%] images/sia-image-bar.png
lost       | copying images... [ 47%] images/sia-toolbar.png
lost       | copying images... [ 52%] images/mia-example.png
lost       | copying images... [ 58%] images/mia-controls1.png
lost       | copying images... [ 64%] images/mia-controls2.png
lost       | copying images... [ 70%] images/mia-example-zoom.png
lost       | copying images... [ 76%] images/LOSTFeaturesIn40seconds.gif
lost       | copying images... [ 82%] images/labeltree_img.png
lost       | copying images... [ 88%] images/labeltree_csv.png
lost       | copying images... [ 94%] images/lost-eco-system.svg
lost       | copying images... [100%] images/db-changes.png
lost       |
lost       | copying static files... ... done
lost       | copying extra files... done
lost       | dumping search index in English (code: en)... done
lost       | dumping object inventory... done
lost       | build succeeded, 1 warning.
lost       |
lost       | The HTML pages are in build/html.
lost       | /opt/conda/envs/lost/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
lost       |   return f(*args, **kwds)
lost       | /code/backend/lost/cli
lost       | Traceback (most recent call last):
lost       |   File "/code/backend/lost/logic/init/initworker.py", line 1, in <module>
lost       |     from lost.logic.pipeline.worker import init_worker_on_startup
lost       | ModuleNotFoundError: No module named 'lost'
lost       | Traceback (most recent call last):
lost       |   File "/code/backend/lost/logic/init/init_patchsystem.py", line 1, in <module>
lost       |     from lost.db.patches import update_version_log
lost       | ModuleNotFoundError: No module named 'lost'
lost       | [uWSGI] getting INI configuration from wsgi.ini
lost       | Traceback (most recent call last):
lost       |   File "/opt/conda/envs/lost/bin/celery", line 11, in <module>
lost       |     sys.exit(main())
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
lost       |     _main()
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
lost       |     cmd.execute_from_commandline(argv)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
lost       |     super(CeleryCommand, self).execute_from_commandline(argv)))
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
lost       |     argv = self.setup_app_from_commandline(argv)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
lost       |     self.app = self.find_app(app)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 501, in find_app
lost       |     return find_app(app, symbol_by_name=self.symbol_by_name)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/app/utils.py", line 359, in find_app
lost       |     sym = symbol_by_name(app, imp=imp)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 504, in symbol_by_name
lost       |     return imports.symbol_by_name(name, imp=imp)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
lost       |     module = imp(module_name, package=package, **kwargs)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
lost       |     return imp(module, package=package)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/importlib/__init__.py", line 127, in import_module
lost       |     return _bootstrap._gcd_import(name[level:], package, level)
lost       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
lost       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
lost       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
lost       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
lost       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
lost       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
lost       |   File "/code/backend/lost/flaskapp.py", line 2, in <module>
lost       |     from lost import settings
lost       | ModuleNotFoundError: No module named 'lost'
lost       | Traceback (most recent call last):
lost       |   File "/opt/conda/envs/lost/bin/celery", line 11, in <module>
lost       |     sys.exit(main())
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
lost       |     _main()
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
lost       |     cmd.execute_from_commandline(argv)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
lost       |     super(CeleryCommand, self).execute_from_commandline(argv)))
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
lost       |     argv = self.setup_app_from_commandline(argv)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
lost       |     self.app = self.find_app(app)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 501, in find_app
lost       |     return find_app(app, symbol_by_name=self.symbol_by_name)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/app/utils.py", line 359, in find_app
lost       |     sym = symbol_by_name(app, imp=imp)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/bin/base.py", line 504, in symbol_by_name
lost       |     return imports.symbol_by_name(name, imp=imp)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
lost       |     module = imp(module_name, package=package, **kwargs)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
lost       |     return imp(module, package=package)
lost       |   File "/opt/conda/envs/lost/lib/python3.7/importlib/__init__.py", line 127, in import_module
lost       |     return _bootstrap._gcd_import(name[level:], package, level)
lost       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
lost       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
lost       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
lost       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
lost       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
lost       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
lost       |   File "/code/backend/lost/flaskapp.py", line 2, in <module>
lost       |     from lost import settings
lost       | ModuleNotFoundError: No module named 'lost'
I have repeated the same error many times. Is there any problem with my operation?

**Comment by chaoji90** [comment]
If I enter the container through
docker exec -it 48cc97df00bf /bin/bash
then execute python and try to import lost, the same error is also reported.

**Comment by jaeger-j** [comment]
Please clone from branch 1.x -> `git clone -b 1.x https://github.com/l3p-cv/lost.git`

2.x which is currently on master is only working in development mode for now.

**Comment by chaoji90** [comment]
> Please clone from branch 1.x -> `git clone -b 1.x https://github.com/l3p-cv/lost.git`
> 
> 2.x which is currently on master is only working in development mode for now.
It works, thank you.
