### ISSUE TITLE
CSV export is always in Pending state (mia.semiauto_kmeans workflow)

### ISSUE THREAD

**Issue by zmtbnv** [l3p-cv/lost#182]
**Describe the bug**
In multiple occasions the `mia.export_csv.py` is not being triggered to export CSV file (attached image).

**To Reproduce**
1. Start Pipeline
2. Select `mia.semiauto_kmeans`
3. Fill in all required fields, assign dataset and start clustering job
4. Annotate images
5. After clicking `Finish Task` Script `mia.export_csv.py`  should start CSV export job. But instead we get `Pending` box as shown below:
![image](https://user-images.githubusercontent.com/22429559/161987906-a9320606-86d6-4056-bcd5-7da25b17fb60.png)

I checked the element ids inside the container, but the folder seems  is not created. For example, this specific task has Element ID `183`, but `lost/data/instance` dir is missing the folder for this task.
![image](https://user-images.githubusercontent.com/22429559/161989856-3f54cf6d-ea60-46bb-8023-a1d38bde6d8c.png)

I tried `Force Annotation Release`, but it didn't help. 

Is there any way we could manually trigger `mia.export_csv.py` only from within container? Otherwise, we need to regenerate task and go through the manual annotation work again.

**Environment**
20.04-Ubuntu

Any guidance would be much appreciated. Thank you.

**Comment by jaeger-j** [comment]
Hi @zmtbnv,

to fix your problem, there are two possible workarounds:

## Trigger Script Manually
1. Get the Pipeline Element ID of the `mia.export_csv.py` script you want to trigger (see Pipeline GUI). 
2. Log into the docker container: `docker exec -it lost bash`
3. Trigger the `mia.export_csv.py` script via command line: `python3 /home/lost/data/pipes/mia/export_csv.py --idx ID_FROM_STEP_1`

## Use the instant_export pipeline:
1. Log into the docker container: `docker exec -it lost bash`
2. Import instant_export pipeline: `import_pipe_project.py /code/backend/lost/pyapi/examples/pipes/instant_export/`
3. Get the Pipeline Element ID of the AnnotationTask you want to export (see Pipeline GUI above)
4. Start the `instant_export.export_annos` pipeline in GUI -> Set `pe_id` of the annotation task you want to export in `instant_export.get_annotask.py` script dialog (see below):
![image](https://user-images.githubusercontent.com/37367934/162002172-e5b2b362-f339-4d8a-a901-475207103335.png)
![image](https://user-images.githubusercontent.com/37367934/162000482-64918103-35a8-4db1-ad2d-22665afeeb95.png)

Hope this works for you.

Best,
Jonas

**Comment by zmtbnv** [comment]
Both approaches worked. Thank you so much, Jonas!
