### ISSUE TITLE
SIA: Polygon getting squeezed when dragged to image border and further

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#2]
**Describe the bug**
When i draw the whole polygon twoards the image edge the polygon gets squeezed on the location of edge contact. Means that the points of the polygon do not cross the edge of the image but with further dragging the other points do move and thus the polygon gets squeezed. 
Propably the same with bounding boxes and lines.

**To Reproduce**
1. select polygon
2. drag it towards an image border and further

**Expected behavior**
Not only the point but the whole polygon should not be further moveable when one point edges the images.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Comment by gereonreus** [comment]
That polygons get squeezed is the desired behavior of SIA.
