### ISSUE TITLE
new annotation in SIA sometimes spawned at shifted position

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#22]
**Describe the bug**
Sometime when creating new annotations the new annotation is not places where the user clicked initially.

**To Reproduce**
1. Go into SIA annotation task
2. Select BBox Tool
3. Right click and drag a new BBox 

**Expected behavior**
The origin of the new BBox should be where the user clicked initially.

**Desktop (please complete the following information):**
 - OS: Win10 x86_64
 - Browser Chrome
 - Version 72

**Comment by cartok** [comment]
Does this happen in browser full screen mode or after switching it on off?

**Comment by 0loid** [comment]
No, it also happens with a freshly opened browser.

**Comment by jaeger-j** [comment]
This issue should be fixed in version 1.0.0-alpha.0
