### ISSUE TITLE
changing of label not saved on prelabeled data

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#23]
**Describe the bug**
When only changing the the label of an pre annotated image the changes are not saved.

**To Reproduce**
1. Start a SIA task with prelabel data
2. Go to an image with existing label
3. Select an annotation
4. Change the label
5. Go to next image
6. Go back to previous image
7. See the old label on the changed annotation

This does not happend if the annotation is modified (moved, resized) after the label change.

**Expected behavior**
The label should be saved after changing it without modifing the annotation

**Desktop (please complete the following information):**
 - OS: Win64 x86_64
 - Browser Chrome
 - Version 72

**Comment by ShroukMansour** [comment]
@0loid How can I start a task with a prelabeled data?
