### ISSUE TITLE
Using the browsers zoom function changes the shown size of annotation in SIA

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#24]
**Describe the bug**
Using the browsers zoom function changes the shown size of annotation in SIA

**To Reproduce**
1. Go into SIA annotation task
2. Create a label and make it active
3. use browsers zoom function (CTRL+MouseScrollWheel or CRTL+ '+'/'-'
4. see changing W,H,X,Y values.

**Expected behavior**
Consitent W,H,X,Y values for unchanged labels

**Desktop (please complete the following information):**
 - OS: Win10 x86_64
 - Browser Chrome
 - Version 72

**Comment by gereonreus** [comment]
The W,H,X,Y values refer to the pixels displayed in the browser. In the database, the values are always stored relative to the image size. 
The specification of the W,H,X,Y values is correct in principle, but may cause confusion. 
Is it possibly even useful to hide this information completely for the next versions ?

**Comment by 0loid** [comment]
No, hiding the values is not be useful. Annotators may have some guideline to not label objects smaller some width or height values. The displayed values should help them to decide if they need to label the object or not.

**Comment by gereonreus** [comment]
Thank you for describing this use case !
These minds will be part of the new SIA Rewrite.

**Comment by jaeger-j** [comment]
This issue should be fixed in version 1.0.0-alpha.0
