### ISSUE TITLE
New annotation under the minArea property of SIA can't be modified

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#25]
**Describe the bug**
A new annotation whose size is smaller than the minArea property can't be edited.

**To Reproduce**
1. Create SIA task with minArea of 400
2. Create an annotation smaller than 20x20 pix
3. try to enlarge

**Expected behavior**
Either the creation of small annotations should be rejected, or it should be possible to enlarge small objects

**Desktop (please complete the following information):**
 - OS: Win64 x86_64
 - Browser Chrome
 - Version 72

**Comment by gereonreus** [comment]
MinArea is not yet supported. This feature is planned for later versions.
The current configuration possibilities of a SIA Annotation Task can be found here: 
https://lost.readthedocs.io/en/latest/all_about_pipelines.html#annotask-element

**Comment by 0loid** [comment]
Ok, it's already or still in the following pipeline example. It's also working in the way, that you can not shrink an exsisting annotation below this threshold.
lost/backend/lost/pyapi/examples/pipes/all_elements/all_element_pipe.json

**Comment by jaeger-j** [comment]
The minArea feature is now/again supported, starting with version 1.0.0-alpha.0
