### ISSUE TITLE
Moving the zoomed image view in SIA leads to losing the focus on selected annotation

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#26]
**Describe the bug**
When using the zoom function of the SIA Editor the view can be moved by click+drag. However the focus of a selected annotation is lost when using it.

**To Reproduce**
1. Open a SIA task
2. zoom into the image using the mouse scroll wheel
3. select or create an annotation and make it active
4. move the image view area by click and drag
5. see the lost focus 

**Expected behavior**
Keeping the focus on the annotation while dragging the view. 

**Desktop (please complete the following information):**
 - OS: Win64 x86_64
 - Browser Chrome
 - Version 72

**Comment by jaeger-j** [comment]
This issue should be fixed in version 1.0.0-alpha.0
