### ISSUE TITLE
Finishing an annotation task requires actions by every user ever active in this task

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#27]
**Describe the bug**
The annotation task logic reserves images for an active user. Those reservations are not released after inactivity. This leads to the need that every user who ever opened the task needs to login at the end and finish the reserved images

**To Reproduce**
1. Create an SIA task for at least two users
2. Login as User 1
3. Open the annotation task
4. Logout User 1
5. Login as User 2
6. Start and try to finish the annotation task
7. one the "last" image click "finish"
8. a pop up apears which tells "not finished" yet
9. task can only be finished by user 1

**Expected behavior**
- reserved images should be released by using the logout button
- reserved images should be released after a timeout period like the automatic logout
- one active user left should be able to finish the annotation task

**Desktop (please complete the following information):**
 - OS: Win64 x86_64
 - Browser Chrome
 - Version 72

**Comment by gereonreus** [comment]
The error could be partially corrected in v 0.0.2:
When two users annotate (Annotator 1 and Annotator 2) and one of them logs out (Annotator 2), its annotations are now completely released to the other users.

However, Annotator 1 will soon have the images previously reserved by Annotator 2 inserted into its annotation process. Once this is the case, Annotator 1 must annotate until he sees the images he has already annotated. Then he has to press the button "go to last edited" in order not to look through all already labelled images again.

Under the current SIA reimplementation, the bug will be completely fixed.

**Comment by rgangu** [comment]
Just to make sure, however, is the timeout for the users a default value presently? Is there one existent? @jaeger-j

**Comment by gereonreus** [comment]
@rgangu 
See if this article can help you:
https://github.com/l3p-cv/lost/issues/94#issuecomment-684783729
