### ISSUE TITLE
SIA image size very restriced by UI constrains which make SIA hardly usable on some devices

### ISSUE THREAD

**Issue by 0loid** [l3p-cv/lost#28]
**Describe the bug**
The image area is very constrained by the other UI elements. As a result an image of 1200x700 will be about 900x500 px an a "modern" 1920x1080 dektop. This wasts nearly 80% of the availabel screen area. A smaller laptop screen with the same resolution results in even smaller image area, which makes the tool unusable.

**Expected behavior**
Maximise the image area to increase the usability. See my proposal image. When moving all control elements to the left or right, making the top info bar foldable there would be enough space to increase the image size significantly.

However element arrangement depends on the used image. For ultra wide images the proposed arrangement would not be optimal. Maybe the UI should calculate differenz arrangements of the control elements (horizontal or vertical) and than select the arrangement with the biggest resulting image area.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49389637/55876759-b157f900-5b98-11e9-9a29-54e57afffe90.png)

**Comment by gereonreus** [comment]
We know that in SIA the image uses a very small percentage of the total UI. Especially for an annotation tool the focus should be on the image.  
SIA is currently undergoing a fundamental overhaul. This tool is currently the only component in the software that has not yet been implemented with React. The implementation in React is currently under development. In this process a fullscreen feature is also considered, which allows a full utilization of the entire UI.

**Comment by jaeger-j** [comment]
We finished the rewrite of SIA in React and released an alpha with LOST version **1.0.0-alpha.0**.
We focused on maximizing the image size, while keeping the whole image in the view. SIA now also supports a **fullscreen** mode.
We tried to consider your proposal and hope the new version of SIA will fit your needs.
