### ISSUE TITLE
SIA history contains all previous images

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#3]
**Describe the bug**
When  doing SIA the history regarding CTRL+Z contains all previously annotaded images in the session.
This means when pressing CTRL+Z too often you get the history of the previous image into the current image.

**To Reproduce**
1. Annotate two images
2. When finished with the second press CTRL+Z several times until annotations of the previous images
is displayed

**Expected behavior**
Only the annotation history of the current image is displayed to the current image

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 -  Version 71.0.3578.98

**Comment by gereonreus** [comment]
Fixed in 0.0.0
