### ISSUE TITLE
How to backup/restore

### ISSUE THREAD

**Issue by KonradAdamczyk** [l3p-cv/lost#37]
Hi
I want to know how to perform full lost backup. 
Simply backuping [Lost Data Folder - folder choosen during installation ](https://lost.readthedocs.io/en/latest/lost_ecosystem.html) with sudo permissions does not work.
Steps taken to test if it is working:

1. sudo zip -r backup.zip Lost Data Folder
2. Clean installation of LOST `clean_lost` folder
3. Creating user with name `should_not exist_after_restore`
4. LOST shutdown
5. rm -rf `clean_lost` 
6. unzip backup.zip into `clean_lost` 
7. LOST start
8.  `should_not exist_after_restore` still exists and users from backup are not restored

 a)Do I need to backup entire docker container along with Lost Data Folder ? 
 b)Is it somewhat related to docker volume mounting 'rprivate' ?

Many thanks 
Konrad Adamczyk

**Comment by gereonreus** [comment]
Hello KonradAdamczyk,

the docker containers themselves do not hold any data of the web application. 
A look into the Docker Compose File (https://github.com/l3p-cv/lost/blob/master/docker/compose/docker-compose.yml) shows that all data is stored in the ${LOST_DATA} folder specified in .env File. 
So if all Docker containers are deleted, all data is still stored on the host. This folder can also be backed up. For a complete backup it would also be useful to backup the docker-compose.yml and the .env file. 

1.) 
Which folder exactly did you back up ? What does the underlying folder structure look like ? 

2.) 
Did you also change your .env file (path to LOST_DATA) ?

3.) 
How did you shut down lost ? Did you delete the docker containers or just quit ?

Best regards,
Gereon


Translated with www.DeepL.com/Translator

**Comment by KonradAdamczyk** [comment]
1. tree -d -L 3 lost_install/
`lost_install/
├── data
│   ├── csv
│   ├── data
│   │   ├── debug
│   │   ├── instance
│   │   ├── logs
│   │   ├── media
│   │   ├── pipes
│   │   └── sia_history
│   ├── logs
│   ├── my_data
│   ├── mysql
│   │   ├── lost
│   │   ├── mysql
│   │   ├── performance_schema
│   │   └── sys
│   └── rabbitmq
│       ├── config
│       ├── mnesia
│       └── schema
└── docker
`
2. No 

3. Only quit.


Now  I managed to get it working.
Steps I taken:
0. `docker rmi` on lost containers. To have clean working space.
1. `git clone https://github.com/l3p-cv/lost.git`
2. `cd lost/docker/quick_setup/
# python3 quick_setup.py path/to/install/lost
python3 quick_setup.py ~/lost`
3. `unzip backup.zip into ~/lost`
4. Make sure that `.env` file contains proper absolute path to `~/lost` in `LOST_DATA`
and proper `LOST_DB_PASSWORD`
5. `cd ~/lost; docker-compose up`
