### ISSUE TITLE
SIA: Mouse pointer disappears after pressing del and selecting a point simultaneously

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#4]
**Describe the bug**
When selecting a point of a polygon and pressing the key del at the same time the point gets deleted but the mouse pointer at the same time. Means that the mouse pointer is not visible for the SIA area. 

**To Reproduce**
1. Select a point of a polygon and keep the left mouse button pressed
2. Press del to delete the point
3. => Point disappears aswell as your mouse pointer

**Expected behavior**
Only the point disappears but not also the mouse pointer

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - 71.0.3578.98

**Comment by gereonreus** [comment]
Fixed in 0.0.0
