### ISSUE TITLE
Add instant annotation donwload! How to deal with growing datasets?

### ISSUE THREAD

**Issue by Shuai-Xie** [l3p-cv/lost#41]
Let's see this case.

A pipeline has been defined.

But if
- The images in my dataset folder are expanding, but the pipeline annotation progress will not.
- A new class needs to be introduced, but the LabelTree of the pipeline can't be updated.
- I just want to export some already labeled data annotation, but the pipeline makes me have to finish all the annotation task before I export the annotation.

The pipeline is a good character, however, it needs more flexibility.

**Comment by jaeger-j** [comment]
Hi @Shuai-Xie, thank you for your contribution. 

> The images in my dataset folder are expanding, but the pipeline annotation progress will not.

Please use an iterative pipeline to solve this problem. If your dataset is growing, while a pipeline has already been started, you can use [loop elements](https://lost.readthedocs.io/en/latest/all_about_pipelines.html#loop). An possible pipeline flow could be as follows:
1. Select 100 images from your dataset.
2. Perform an annotation task for theses 100 images.
3. A [loop elements](https://lost.readthedocs.io/en/latest/all_about_pipelines.html#loop) jumps back to step 1.

> A new class needs to be introduced, but the LabelTree of the pipeline can't be updated.

Please see my answer to issue #40 

> I just want to export some already labeled data annotation, but the pipeline makes me have to finish all the annotation task before I export the annotation.

That is a nice point. We should **add a button** to each annotation task in our pipeline view **for an instant download of the annotations.**

**Comment by Shuai-Xie** [comment]
Thanks for your detailed reply. I'll try your suggestions right away.

So fast does the GitHub stars of **LOST** increase, That's indeed a promising work.

**Comment by Shuai-Xie** [comment]
> Hi @Shuai-Xie, thank you for your contribution.
> 
> > The images in my dataset folder are expanding, but the pipeline annotation progress will not.
> 
> Please use an iterative pipeline to solve this problem. If your dataset is growing, while a pipeline has already been started, you can use [loop elements](https://lost.readthedocs.io/en/latest/all_about_pipelines.html#loop). An possible pipeline flow could be as follows:
> 
> 1. Select 100 images from your dataset.
> 2. Perform an annotation task for theses 100 images.
> 3. A [loop elements](https://lost.readthedocs.io/en/latest/all_about_pipelines.html#loop) jumps back to step 1.
> 
> > A new class needs to be introduced, but the LabelTree of the pipeline can't be updated.
> 
> Please see my answer to issue #40
> 
> > I just want to export some already labeled data annotation, but the pipeline makes me have to finish all the annotation task before I export the annotation.
> 
> That is a nice point. We should **add a button** to each annotation task in our pipeline view **for an instant download of the annotations.**

Thanks for your detailed reply. I'll try your suggestions right away.

So fast does the GitHub stars of **LOST** increase, That's indeed a promising work.

**Comment by Shuai-Xie** [comment]
Hi @jaeger-j  Thanks for your detailed reply. I'll try your suggestions right away.

So fast does the GitHub stars of **LOST** increase, That's indeed a promising work.

**Comment by avi-vsionai** [comment]
Has there been any development on this issue? I would love to download partial annotations without having completed the entire dataset. For the time being I'll also take any dirty hack.

**Comment by jaeger-j** [comment]
Hi @avi-vsionai,
Please use our [instant export pipeline for now](https://github.com/l3p-cv/lost/tree/master/backend/lost/pyapi/examples/pipes/instant_export). In LOST 2.0 there will be a GUI-button.

**Comment by gereonreus** [comment]
Already implemented on branch 2.x
