### ISSUE TITLE
Pipeline runs cannot be completed

### ISSUE THREAD

**Issue by qianxi0617** [l3p-cv/lost#48]
**Describe the bug**
When I start pipeline sia.semiauto_yolov3,sia.request_yolo_annos.py cannot be finished

**Expected behavior**
Before annotator worked,request annotations using yolov3 predictions

**Screenshots**
![1](https://user-images.githubusercontent.com/44162537/68357684-11c01080-0151-11ea-801a-5162c4d497e7.png)

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: LInux
 - Browser: Chrome

**Comment by jaeger-j** [comment]
Hi @qianxi0617,
Could you please provide these log files for us: `beat.log  flask.log  lost-0.log  lost-cv-0.log`
You will find the files in folder: `path_to_lost/data/logs`
Best, Jonas

**Comment by gereonreus** [comment]
Closed due to inactivity.
