### ISSUE TITLE
Cannot delete pipeline

### ISSUE THREAD

**Issue by qianxi0617** [l3p-cv/lost#49]
**Describe the bug**
Cannot delete pipeline

**Expected behavior**
Pipeline deleted
When I delete the pipeline，the following page is displayed.
**Screenshots**
![2](https://user-images.githubusercontent.com/44162537/68358382-5187f780-0153-11ea-9cdf-c24ee873fd5c.png)
![3](https://user-images.githubusercontent.com/44162537/68358384-5351bb00-0153-11ea-940f-ffd9e43c701f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by jaeger-j** [comment]
Hi @qianxi0617,
Could you please provide these log files for us: `beat.log flask.log lost-0.log lost-cv-0.log`
You will find the files in folder: `path_to_lost/data/logs`
Best, Jonas
