### ISSUE TITLE
Restart a pipeline

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#5]
**Is your feature request related to a problem? Please describe.**
It is unnecessary work to always create a new pipeline in the developing work.

**Describe the solution you'd like**
A simple restart button to restart the pipeline.

**Comment by gereonreus** [comment]
Implemented a "Regenerate Button".

Within the view of a pipeline, pressing the "Regenerate" button will start the pipeline with the same parameters. 
Then you switch to the tabular pipeline overview.
The newly started pipeline can be recognized by the additional #n in the name and by the date.
The old pipeline remains and must be deleted manually, if desired.
Will be part of Release 0.0.0
![screenshot from 2019-02-07 12-07-25](https://user-images.githubusercontent.com/36843962/52407548-f3998700-2ad0-11e9-82c5-688408137400.png)
![screenshot from 2019-02-07 12-08-01](https://user-images.githubusercontent.com/36843962/52407588-08761a80-2ad1-11e9-873a-4fb040fa09cb.png)
