### ISSUE TITLE
Annotations Lost

### ISSUE THREAD

**Issue by zhouyuangan** [l3p-cv/lost#51]
**Describe the bug**
When annotating in Google Chrome, I encountered a loss of the label. At that time, I had already annotated a picture. He had more than 100 polygons. When I clicked the next one, I went back to the annotated picture. He has only 50 polygons, and even all polygons are gone.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome,]
 - Version [22]

**Comment by zhouyuangan** [comment]
@KonradAdamczyk @Baumboon @cartok @gereonreus

**Comment by zhouyuangan** [comment]
please help me, thanks,

**Comment by jaeger-j** [comment]
Hi @zhouyuangan,
could you please provide the LOST version you are using? You will find the LOST_VERSION in the `path_to_lost/docker/.env` file.

**Comment by zhouyuangan** [comment]
@jaeger-j 

`
#=======================#
#=   LOST Basic conig  =#
#=======================#
DEBUG=False
# Add example pipelines and example images =#
ADD_EXAMPLES=True
#= Add also ai pipelines if true. You will need the lost-cv worker to execute these pipelines.= #
ADD_AI_EXAMPLES=True
LOST_VERSION=1.0.0
#= LOST port binding to host machine= #
LOST_FRONTEND_PORT=5073
SECRET_KEY=DHDXVJ1O58M5RZ7Y
#= Path to LOST data in host filesystem= #
LOST_DATA=/data/mlprd/cv_deploy/lost_anno/LOST/data
#=======================#
#= LOST Database conig =#
#=======================#
LOST_DB_NAME=lost
LOST_DB_USER=lost
LOST_DB_PASSWORD=LostDbLost
LOST_DB_ROOT_PASSWORD=LostRootLost
#=======================#
#=   PipeEngine conig  =#
#=======================#
# Interval in seconds for the cronjob to update the pipeline= #
PIPE_SCHEDULE=5
# Intervall in seconds in which a worker should give a lifesign= #
WORKER_BEAT=10
# Timeout in seconds when a worker is considered to be dead= #
WORKER_TIMEOUT=30
#=========================#
#= Your Mail config here =#
#=========================#
#MAIL_SERVER=mailserver.com
#MAIL_PORT=465
#MAIL_USE_SSL=True
#MAIL_USE_TLS=True
#MAIL_USERNAME=email@email.com
#MAIL_PASSWORD=password
#MAIL_DEFAULT_SENDER=LOST Notification System <email@email.com>
#MAIL_LOST_URL=http://mylostinstance.url/
`

**Comment by zhouyuangan** [comment]
This bug is random. I can't guarantee that each picture will lose the annotation information, but from the exported csv file, the number of the label box is counted. I can confirm that the pipeline has lost a lot of label boxes. This is a very serious bug.
