### ISSUE TITLE
Cannot install the app on windows

### ISSUE THREAD

**Issue by IbrahimShamma99** [l3p-cv/lost#55]
When I run docker-compose up it ends up with an error that says:
rabbitmqlost    | 2020-01-23 15:18:03.800377 crash_report        #{label=>{supervisor,start_error},report=>[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{offender,[{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}

and other errors that occurs on the same log file.

**Comment by rgangu** [comment]
I think this may be a case of simply checking the permissions of the /var/lib/rabbitmq/.erlang.cookie file -> if you had set permissions to be accessible by all, this is causing the crash. Change the permissions so only the owner can access it. Perhaps something like this would do the trick.

``` chmod 700 <PATH_TO_.erlang.cookie FILE> ```

**Comment by gereonreus** [comment]
Rabbitmq is no longer used in LOST 2.x.
