### ISSUE TITLE
Question: Can I import previously annotated dataset to update it's labeles

### ISSUE THREAD

**Issue by ShroukMansour** [l3p-cv/lost#58]
This is actually a question, not a bug but I didn't find `how to` label. 
I need to update some annotated images I annotated before but don't know how to do that. when I searched in the docs I've found `Reading Annotations` part as a script. Is there an easier way to do that as writing scripting looks unfamiliar to me?

**Comment by jaeger-j** [comment]
Hi @ShroukMansour,
right now there is no other way than using a script for that. We will provide a review pipeline for you in the next version.

**Comment by jaeger-j** [comment]
Please check our new review tool: https://lost.readthedocs.io/en/1.2/annotation_review.html
