### ISSUE TITLE
Add shortcut for SIA next/prev image

### ISSUE THREAD

**Issue by fran6co** [l3p-cv/lost#67]
**Is your feature request related to a problem? Please describe.**
Having a shortcut to move around the images would be a big usability improvement given that the toolbar moves depending on the image resolution. Also it speed ups annotations

**Describe the solution you'd like**
Just add a shortcut for next/prev images (arrow keys?)

**Comment by jaeger-j** [comment]
Hi @fran6co,
this is a nice idea. We will implement the shortcut in version 1.2.0.
Best,
Jonas
