### ISSUE TITLE
Pipeline stuck after running

### ISSUE THREAD

**Issue by Sagar1094** [l3p-cv/lost#70]
Pipeline stuck after running. Attaching a screenshot and log files. Please help
![Capture](https://user-images.githubusercontent.com/54572031/79558128-4e5d4400-80c1-11ea-86ce-9ca8e15ed6ea.JPG)
[uswgi.log](https://github.com/l3p-cv/lost/files/4492225/uswgi.log)
[beat.log](https://github.com/l3p-cv/lost/files/4492227/beat.log)
[flask.log](https://github.com/l3p-cv/lost/files/4492228/flask.log)
[lost-0.log](https://github.com/l3p-cv/lost/files/4492229/lost-0.log)

**Comment by jaeger-j** [comment]
Hi @Sagar1094,
the problem seams to be that the LOST-Containers do not get a connection to the RabbitMQ message broker. In most cases the problem can be solved by removing all LOST related docker containers and recreating them. Your persistent data in the LOST project folder will be preserved. Please perform the following steps to do so:
```bash
# Remove all LOST related docker containers 
docker rm -f $(docker ps -aq --filter name=lost)
# Restart LOST
cd /path/to/lost/docker
docker-compose up
```
Please provide some feedback, if this solved your problem.

Best,
Jonas

**Comment by hunterhonda** [comment]
Hi @jaeger-j ,
I tried the above steps, the issue still persists.

**Comment by pepijnob** [comment]
Hi @hunterhonda ,
I have the same issue, have you found a solution?
thanks,
