### ISSUE TITLE
Watch / Edit done annotations

### ISSUE THREAD

**Issue by Daniel595** [l3p-cv/lost#75]
**Is your feature request related to a problem? Please describe.**
After finishing annotation tasks it often happens that annotation failures can be examined. It would be very helpfull if annotations could be edited after finishing the task. A possibility to watch the done annotations with LOST would also be helpful and friendly.

**Describe the solution you'd like**
It should be possible to restart the annotation task. The already done annotations should be loaded.

**Comment by jaeger-j** [comment]
Hi @Daniel595,
thank you for your contribution :-)
Please check out our new Review-Tool (LOST version 1.2.0): https://lost.readthedocs.io/en/1.2/annotation_review.html
