### ISSUE TITLE
start LOST as a non-root user

### ISSUE THREAD

**Issue by Aequalitas** [l3p-cv/lost#8]
**Is your feature request related to a problem? Please describe.**
As of now LOST has to be started as a root user. Which is not advisable and usefull in a wider userbase.

**Describe the solution you'd like**
The possibility to run LOST as a non-root user as in a user-group in linux

**Comment by gereonreus** [comment]
LOST 2.x can bet setup without docker inside your own environment:
https://github.com/l3p-cv/lost/tree/master/setup
