### ISSUE TITLE
Annotation Task - timeout warning

### ISSUE THREAD

**Issue by Daniel595** [l3p-cv/lost#81]
**Is your feature request related to a problem? Please describe.**
During an annotation some kind of session timeout apparently occurs. This leads into loss of the done and unsaved annotations which is very painfull.

**Describe the solution you'd like**
A clearly visible warning for the upcomming timeout. 

**Additional context**
Maybe some kind off session extension options. 
Make timeout configurable by pipeline designer by arguments in annotation task.

**Comment by gereonreus** [comment]
Already implemented on branch 2.x
