### ISSUE TITLE
Provide your own dockerfile

### ISSUE THREAD

**Issue by hollowgalaxy** [l3p-cv/lost#83]
**Is your feature request related to a problem? Please describe.**
want to do pip installs and don't want to modify the original dockerfile
**Describe the solution you'd like**
including a `--dockefile` to specify path to the dockerfile
**Describe alternatives you've considered**

**Additional context**

**Comment by gereonreus** [comment]
Hi @hollowgalaxy 

Sorry for that late reply !
After a period of inactivity in this repo we made it to our goal to develop the new LOST 2.x version.

If your issue is still relevant for you, please reopen this issue and give us more information.
