### ISSUE TITLE
Flask-Restplus depreciated, move to Flask-RestX

### ISSUE THREAD

**Issue by larsbotics** [l3p-cv/lost#89]
**Is your feature request related to a problem? Please describe.**
As I've went through the project and tried to analyze the structure of it, I came by the Flask-Restplus repository (which this project is based on). In their README, they write that:
**This project has been forked to Flask-RESTX and will be maintained by by the python-restx organization. Flask-RESTPlus should be considered unmaintained.**

**Describe the solution you'd like**
To guarantee that future releases of LOST are always up to date, it might be a good idea to move to Flask-RestX.
Apparently, the only thing that needs to be changed is the import source (but haven't done deeper research).

Links:
https://github.com/noirbizarre/flask-restplus
https://github.com/python-restx/flask-restx

**Comment by gereonreus** [comment]
Adapted on branch 2.x
