### ISSUE TITLE
Multiple annotation of same images in multi-user annotation 

### ISSUE THREAD

**Issue by Daniel595** [l3p-cv/lost#90]
**Describe the bug**
The same image-annotation is requested multiple times on different users. 

**To Reproduce**
1. start a pipeline containing anno-task assigned to a group
2. start anno task with group-user1
3. log-in group-user2 and start anno-task
4. **user 2 gets the same image as user 1 already has**
5. when continuing the pipeline, the bug doesn't occur anymore
6. the bug occurs one time for every 'fresh' user

**Additional context**
The bug only occurs one time per user after starting an anno-task the very first time. It seems like the first image is determined in a different way than the later ones.

**Comment by gereonreus** [comment]
Can't be reproduced in 2.x anymore.
