### ISSUE TITLE
Blank screen when data source is a symbolic link

### ISSUE THREAD

**Issue by starkgate** [l3p-cv/lost#91]
**Describe the bug**
If the media folder in `lost/data/data/media/` is a symbolic link, the website displays an empty screen with no error message in the log.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 x64 Xfce
 - Browser: Firefox 78.0.2 x64

**Comment by gereonreus** [comment]
Fixed in LOST V2:
New datasource management allows to integrate external data (ssh / ftp, s3 bucket, blobstorage, local filesystem) with the help of additional datasources.
