### ISSUE TITLE
Script parsing fails when list/dictionary literals are not valid JSON

### ISSUE THREAD

**Issue by jeremyadamsfisher** [l3p-cv/lost#97]
**Describe the bug**
When importing a pipeline with `{import,update}_pipe_project.py`, some script constants that are valid python literals cannot be parsed. Although the overall script parsing succeeds, this leads to errors downstream:
- When `ENVS` are invalid JSON, the script hangs on execution
- When the `ARGUMENTS` are invalid JSON, the script can be run, but the arguments cannot be changed from the frontend

**To Reproduce**: script hangs on execution
1. In any script, make the constant a valid python literal, but an invalid JSON. For example:
```python
ENVS = ["custom-worker"]  # comment about custom worker
```
2. This results in a `json.decoder.JSONDecodeError`
3. Script hangs indefinitely
![image](https://user-images.githubusercontent.com/12537747/89659347-c08aac00-d89d-11ea-988f-82ae2e5f4b63.png)

**To Reproduce**: Arguments cannot be changed from the frontend

1. In any script, make `ARGUMENTS` a valid python literal, but an invalid JSON. For example:
```python
ARGUMENTS = {
    # comments are not allowed in JSON
    "file_name": {
        "value": "annos.csv",
        "help": "Name of the file with exported bbox annotations."
    }, # <- also, notice the trailing comma
}
```
2. This results in a `json.decoder.JSONDecodeError`
3. Front-end no longer displays "file_name" as an argument

![image](https://user-images.githubusercontent.com/12537747/89559083-29611e00-d7e3-11ea-85d8-d4e55ac96494.png)
![image](https://user-images.githubusercontent.com/12537747/89652010-d5157700-d892-11ea-9fd6-26d783688152.png)

**Expected behavior**
- Front-end should display arguments
- `ARGUMENTS` and `ENVS` hould be parsed like python literals, raise a more descriptive error or fail outright.

**Additional context**
It seems to me that [this line](https://github.com/l3p-cv/lost/blob/61e8203a80f15a46916da6b9dc1e56c2a3c36f5b/backend/lost/logic/script.py#L112) could simply be changed to `arg_dict = ast.literal_eval(args)` to fix both issues. I've tested this minimally and it seems to work.

I would be happy to write some unit tests and make a PR, if there is interest.

**Comment by jaeger-j** [comment]
Hi @jeremyadamsfisher,
thank you for your contribution. Your proposed solution will be released with version 1.3.0. 
It would be great if you write some unit test.
Best,
Jonas
